### ISSUE TITLE
npm dopublish needs to be cross platform

### ISSUE THREAD

**Issue by richardjr** [nautoguide/ourthings#24]
The npm publish doesn't work from a windows box

We need a cross platform script for this, useful guide:

https://medium.freecodecamp.org/introduction-to-npm-scripts-1dbb2ae01633

**Comment by ng-dan** [comment]
What doesn't work? It works fine on Windows:
![https://i.dan-jones.me.uk/yNZfTlIP.png](https://i.dan-jones.me.uk/yNZfTlIP.png)
