### ISSUE TITLE
Erroring on creating a prepared api.post() unless it is ran instantly first

### ISSUE THREAD

**Issue by MidgetJake** [nautoguide/ourthings#64]
Attempting to create a prepared command for an api post request. However, it errors out and freezes up the entire queue unless the api call is called instantly first.

The command that I attempted at first is:
```js
@api.post({
    "url": "{{config.api}}",
    "body": {
        "_token": "{{config.token}}",
        "schema": "adventuresyndicate",
        "app": "map_tracker", 
        "api": "feature_api",
        "action": "add", 
        "payload": {
            "_filters": [{
                "type": "json", 
                "data": "features", 
                "item": "attributes", 
                "prefix": "F", 
                "filter": {
                    "feature_type": "distance_record",
                    "distance": "{{!memory.mileageForm.distance}}",
                    "org_id":"{{!memory.mileageForm.schoolID}}",
                    "org_rider":"{{!memory.mileageForm.riderName}}"
                }
            }
        ]}
    }
}, {
        "queuePrepare": "submitMileage", 
        "memoryMode": "Session",
        "memoryName":"mileagePost"
    }
);
```

However this gives the error:
```js
Error: Dom Element find failed for [[data-queueable=CMD17]]
```

It appears to be try to bind the command to an element however it is not within one. The above command works if `"queueRun":"Instant"` is added to the options but the api call then gets run when the template is loaded when it is marked to be prepared.

**Comment by richardjr** [comment]
This should now be fixed. Previously you could only have prepared queues in the init template but now you cna have them anywhere.
